language: python
os:
- linux
python:
- 3.6
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
before_install:
- sudo apt-get update
- sudo apt-get -y install python3-pip python3-setuptools
- sudo pip3 install awscli
install:
- pip install $(cat requirements.txt $(find lib -name requirements.txt | sort) | sort | uniq | sed 's/ *== */==/g')
- pip install -r requirements-dev.txt
script:
- ./test.sh
after_success:
- echo "codecov will exec here"
deploy:
- provider: script
  script: bash ./.travis/build-deploy.sh prod us-east-1
  on:
    branch: master
notifications:
  email: false