replicaCount: 1
service:
  name: chief-keeper
  port: 8080
  type: ClusterIP
  containerPort: 8080
  tls:
    enabled: false
  # Add metrics port for Prometheus
  metrics:
    name: metrics
    port: 9090
    containerPort: 9090
deployment:
  enabled: true
  volumes:
    - name: db
      mountPath: /opt/keeper/chief-keeper/chief_keeper/database
      provisioner: efs.csi.aws.com
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
      parameters:
        provisioningMode: efs-ap
        fileSystemId: fs-01b6896d4c2a6deb6
        directoryPerms: "700"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - on-demand
image:
  pullPolicy: Always
serviceAccount:
  create: false
ingress:
  enabled: false
podAnnotations:
  reloader.stakater.com/auto: "true"
  # Add Prometheus scraping annotations
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"
  prometheus.io/path: "/metrics"
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi
autoscaling:
  enabled: false
env:
  # Add metrics port environment variable
  METRICS_PORT:
    type: kv
    value: "9090"
  PRIMARY_ETH_RPC_HOST:
    type: parameterStore
    name: primary-eth-rpc-host
    parameter_name: /eks/maker-prod/chief-keeper/primary-eth-rpc-host
  BACKUP_ETH_RPC_HOST:
    type: parameterStore
    name: backup-eth-rpc-host
    parameter_name: /eks/maker-prod/chief-keeper/backup-eth-rpc-host
  ETH_ACCOUNT_KEY:
    type: kv
    value: "key_file=/opt/keeper/chief-keeper/secrets/keystore.json,pass_file=/opt/keeper/chief-keeper/secrets/password.txt"
  BLOCKCHAIN_NETWORK:
    type: kv
    value: "mainnet"
  CHIEF_DEPLOYMENT_BLOCK:
    type: kv
    value: "14374534"
  ETH_FROM_ADDRESS:
    type: parameterStore
    name: eth-from-addr-mainnet
    parameter_name: /eks/maker-prod/chief-keeper/eth-from-addr-mainnet
  SECRET_KEY:
    type: parameterStore
    name: secret-key-mainnet
    parameter_name: /eks/maker-prod/chief-keeper/secret-key-mainnet
  SECRET_PASS:
    type: parameterStore
    name: secret-pass-mainnet
    parameter_name: /eks/maker-prod/chief-keeper/secret-pass-mainnet
  BLOCKNATIVE_API_KEY:
    type: parameterStore
    name: blocknative-api-key
    parameter_name: /eks/maker-prod/chief-keeper/blocknative-api-key
externalSecrets:
  clusterSecretStoreName: maker-prod
livenessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - ps -ef | grep chief-keeper
  initialDelaySeconds: 5
  periodSeconds: 30
readinessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - ps -ef | grep chief-keeper
  initialDelaySeconds: 5
  periodSeconds: 30
